# Generated by Django 4.2.7 on 2025-09-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capDatos', '0002_numberlandmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberlandmark',
            old_name='numero',
            new_name='numeros',
        ),
    ]
